package cds.allsky;

public enum Action {
   
   INDEX, TILES, JPEG, MOC, MOCINDEX, MOCHIGHT, ALLSKY, GZIP, GUNZIP,
   FINDER,  // Pour compatibilité
   CLEAN, CLEANINDEX, CLEANTILES, CLEANFITS, CLEANJPEG, CHECK,
   RGB, TREE, MERGE, PROGEN,
   ABORT, PAUSE, RESUME,
   MOC10
	
}
